---

- name: Set up my computer
  hosts: localhost
  connection: local

  vars:
    package_ver:
      fzf: 0.53.0
      git_delta: 0.17.0
      neovim: 0.10.0
    fonts_ver:
      space_mono: 3.2.1

  tasks:
    - name: Create some directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - ~/.cache/nvim/undo
        - ~/.config-backup
        - ~/.gdbinit.d/
        - ~/.local/git
        - ~/.local/share/nvim/site/autoload
        - ~/.zsh/cache

    - name: Install packages
      ansible.builtin.include_tasks: tasks/packages.yml

    - name: Install my dotfiles
      ansible.builtin.include_tasks: tasks/dotfiles.yml

    - name: Install my tools
      ansible.builtin.include_tasks: tasks/tools.yml

    - name: Misc tasks
      ansible.builtin.include_tasks: tasks/misc.yml
