---

- name: Set up my computer
  hosts: localhost
  connection: local

  vars:
    package_ver:
      fzf: 0.53.0
      git_delta: 0.17.0
      neovim: 0.10.0

  tasks:
    - name: Create some directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - ~/.cache/nvim/undo
        - ~/.config-backup
        - ~/.local/git
        - ~/.local/share/nvim/site/autoload
        - ~/.zsh/cache

    - name: Install packages
      ansible.builtin.include_tasks: tasks/packages.yml

    - name: Install my dotfiles
      ansible.builtin.include_tasks: tasks/dotfiles.yml

    - name: Install my tools
      ansible.builtin.include_tasks: tasks/tools.yml

    - name: Link batcat to bat
      ansible.builtin.file:
        src: /usr/bin/batcat
        dest: ~/.local/bin/bat
        state: link
      when: ansible_facts['distribution'] == "Debian"

    - name: Install cronjob to purge old undo files every hour
      ansible.builtin.cron:
        name: Purge undo files
        minute: 0
        hour: "*"
        job: >-
          find ~/.cache/nvim/undo
          -type f
          -mtime +7
          -exec rm {} \;
