---

- ansible.builtin.stat:
    path: ~/.cfg
  register: dotfiles_repository

- name: Install my dotfiles
  block:
    - name: Clone my dotfiles repository
      ansible.builtin.git:
        repo: https://github.com/clemfou/Config.git
        dest: ~/.cfg
        bare: true

    - name: Checkout the config
      ansible.builtin.shell: |
        git --git-dir="$HOME"/.cfg --work-tree="$HOME" checkout
      ignore_errors: yes
      args:
        executable: /bin/bash
      register: checkout_result

    - name: Backup pre-existing dot files
      block:
        - ansible.builtin.shell: |
            git --git-dir="$HOME"/.cfg --work-tree="$HOME" checkout 2>&1 | \
            egrep "\s+\." | awk {'print $1'} | \
            xargs -I{} sh -c 'mkdir -p "$HOME/.config-backup/$(dirname {})" && mv "$HOME/{}" "$HOME/.config-backup/{}"'
          args:
            executable: /bin/bash

        - ansible.builtin.shell: |
            git --git-dir="$HOME"/.cfg --work-tree="$HOME" checkout
          args:
            executable: /bin/bash
      when: checkout_result.failed

    - name: Set Git to not show untracked files
      ansible.builtin.shell: |
        git --git-dir="$HOME"/.cfg --work-tree="$HOME" config status.showUntrackedFiles no
      args:
        executable: /bin/bash

  when: not dotfiles_repository.stat.exists
