---

- name: Install my favorite fonts
  block:
    - name: Ensure font directories exist
      ansible.builtin.file:
        path: "/usr/local/share/fonts/ttf/{{ item }}"
        state: directory
      loop:
        - spacemono
        - sourcecodepro

    - name: Download and unarchive SourceCodePro font
      ansible.builtin.unarchive:
        src:
          "https://github.com/ryanoasis/nerd-fonts/releases/\
          download/v{{ fonts_ver.source_code_pro }}/SourceCodePro.zip"
        dest: /usr/local/share/fonts/ttf/sourcecodepro
        exclude:
          - "*.txt"
          - "*.md"
        remote_src: true
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Download and unarchive SpaceMono font
      ansible.builtin.unarchive:
        src:
          "https://github.com/ryanoasis/nerd-fonts/releases/\
          download/v{{ fonts_ver.space_mono }}/SpaceMono.zip"
        dest: /usr/local/share/fonts/ttf/spacemono
        exclude:
          - "*.txt"
          - "*.md"
        remote_src: true
      ignore_errors: "{{ ansible_check_mode }}"
  become: true

- name: Link batcat to bat
  ansible.builtin.file:
    src: /usr/bin/batcat
    dest: ~/.local/bin/bat
    state: link
  when: ansible_facts['distribution'] == "Debian"
