---

- name: Install my favorite fonts
  block:
    - name: Ensure font directories exist
      ansible.builtin.file:
        path: "/usr/local/share/fonts/ttf/{{ item }}"
        state: directory
      loop:
        - spacemono
        - sourcecodepro

    - name: Download and unarchive SourceCodePro font
      ansible.builtin.unarchive:
        src:
          "https://github.com/ryanoasis/nerd-fonts/releases/\
          download/v{{ fonts_ver.source_code_pro }}/SourceCodePro.zip"
        dest: /usr/local/share/fonts/ttf/sourcecodepro
        exclude:
          - "*.txt"
          - "*.md"
        remote_src: true

    - name: Download and unarchive SpaceMono font
      ansible.builtin.unarchive:
        src:
          "https://github.com/ryanoasis/nerd-fonts/releases/\
          download/v{{ fonts_ver.space_mono }}/SpaceMono.zip"
        dest: /usr/local/share/fonts/ttf/spacemono
        exclude:
          - "*.txt"
          - "*.md"
        remote_src: true
  become: true

- name: Link batcat to bat
  ansible.builtin.file:
    src: /usr/bin/batcat
    dest: ~/.local/bin/bat
    state: link
  when: ansible_facts['distribution'] == "Debian"

- name: Install cronjob to purge old undo files every hour
  ansible.builtin.cron:
    name: Purge undo files
    minute: 0
    hour: "*"
    job: >-
      find ~/.cache/nvim/undo
      -type f
      -mtime +7
      -exec rm {} \;
